<?php

namespace Tests\Feature\Domain\Identity;

use App\Domain\Platform\Models\AuditEntry;
use App\Models\User;
use Illuminate\Foundation\Testing\LazilyRefreshDatabase;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Password;
use Tests\TestCase;

/**
 * E3.8: recovery codes (single use, stored encrypted, regeneration invalidates the previous set, audited)
 * and no way around MFA by changing the e-mail or the password or by recovering the account.
 */
class MfaSafeguardsTest extends TestCase
{
    use LazilyRefreshDatabase;

    private const PASSWORD = 'correct-horse-battery';

    private const NEW_PASSWORD = 'another-horse-battery-staple';

    private function account(): User
    {
        return User::factory()->withTwoFactor()->create(['email' => 'anna@example.test', 'password' => self::PASSWORD]);
    }

    private function loginWithRecoveryCode(string $code, string $password = self::PASSWORD): void
    {
        $this->post('/login', ['email' => 'anna@example.test', 'password' => $password])->assertRedirect('/two-factor-challenge');
        $this->post('/two-factor-challenge', ['recovery_code' => $code]);
    }

    private function logout(): void
    {
        $this->app['auth']->guard('web')->logout();
        $this->flushSession();
    }

    public function test_recovery_code_works_only_once_and_its_use_is_audited(): void
    {
        $account = $this->account();
        $code = $account->recoveryCodes()[0];

        $this->loginWithRecoveryCode($code);
        $this->assertAuthenticatedAs($account);
        $this->logout();

        $this->loginWithRecoveryCode($code);
        $this->assertGuest();
        $this->assertSame(1, AuditEntry::query()->where(['action' => 'account.updated', 'reason' => 'recovery code used at login'])->count());
    }

    public function test_recovery_codes_are_stored_encrypted_and_never_in_the_audit(): void
    {
        $account = $this->account();
        $stored = DB::table('users')->where('id', $account->id)->value('two_factor_recovery_codes');

        foreach ($account->recoveryCodes() as $code) {
            $this->assertStringNotContainsString($code, $stored);
        }
        $this->loginWithRecoveryCode($account->recoveryCodes()[0]);
        $entry = AuditEntry::query()->where('reason', 'recovery code used at login')->sole();
        $this->assertSame('[REDACTED]', $entry->after_values['two_factor_recovery_codes']);
    }

    public function test_regenerating_codes_invalidates_the_previous_ones_and_is_audited(): void
    {
        $account = $this->account();
        $old = $account->recoveryCodes();

        $this->actingAs($account)->withSession(['auth.password_confirmed_at' => time()])->postJson('/user/two-factor-recovery-codes')->assertOk();
        $new = $account->fresh()->recoveryCodes();
        $this->assertCount(8, $new);
        $this->assertSame([], array_intersect($old, $new));
        $this->assertSame(1, AuditEntry::query()->where(['action' => 'account.updated', 'reason' => 'recovery codes regenerated by account holder'])->count());
        $this->logout();

        $this->loginWithRecoveryCode($old[0]);
        $this->assertGuest();
        $this->loginWithRecoveryCode($new[0]);
        $this->assertAuthenticatedAs($account);
    }

    public function test_regenerating_codes_requires_a_recent_password_confirmation(): void
    {
        $account = $this->account();
        $old = $account->recoveryCodes();

        $this->actingAs($account)->postJson('/user/two-factor-recovery-codes')->assertStatus(423);

        $this->assertSame($old, $account->fresh()->recoveryCodes());
    }

    public function test_account_recovery_by_password_reset_keeps_mfa_and_still_asks_for_the_code(): void
    {
        $account = $this->account();
        $token = Password::broker()->createToken($account);

        $this->post('/reset-password', ['token' => $token, 'email' => 'anna@example.test', 'password' => self::NEW_PASSWORD, 'password_confirmation' => self::NEW_PASSWORD])->assertRedirect('/login');

        $this->assertGuest();
        $this->assertTrue($account->fresh()->hasConfirmedTwoFactor(), 'Reset hasła nie wyłącza MFA.');
        $this->post('/login', ['email' => 'anna@example.test', 'password' => self::NEW_PASSWORD])->assertRedirect('/two-factor-challenge');
        $this->assertGuest();
    }

    public function test_password_change_keeps_mfa(): void
    {
        $account = $this->account();

        $this->actingAs($account)->put('/user/password', ['current_password' => self::PASSWORD, 'password' => self::NEW_PASSWORD, 'password_confirmation' => self::NEW_PASSWORD])->assertSessionHasNoErrors();
        $this->logout();

        $this->assertTrue($account->fresh()->hasConfirmedTwoFactor());
        $this->post('/login', ['email' => 'anna@example.test', 'password' => self::NEW_PASSWORD])->assertRedirect('/two-factor-challenge');
        $this->assertGuest();
    }

    public function test_account_email_cannot_be_changed_to_take_over_or_drop_mfa(): void
    {
        $account = $this->account();

        $this->actingAs($account)->putJson('/user/profile-information', ['email' => 'intruz@example.test', 'given_name' => 'X', 'family_name' => 'Y'])->assertNotFound();
        $this->actingAs($account)->put('/account', ['email' => 'intruz@example.test', 'given_name' => 'Anna', 'family_name' => 'Nowak']);
        $this->logout();

        $this->assertSame('anna@example.test', $account->fresh()->email);
        $this->assertTrue($account->fresh()->hasConfirmedTwoFactor());
        $this->post('/register', ['given_name' => 'Anna', 'family_name' => 'Nowak', 'email' => 'anna@example.test', 'password' => self::NEW_PASSWORD, 'password_confirmation' => self::NEW_PASSWORD])->assertSessionHasErrors('email');
        $this->assertSame(1, User::query()->where('email', 'anna@example.test')->count(), 'Drugie konto na ten sam adres nie powstaje.');
    }

    public function test_disabling_mfa_requires_a_recent_password_confirmation(): void
    {
        $account = $this->account();

        $this->actingAs($account)->deleteJson('/user/two-factor-authentication')->assertStatus(423);

        $this->assertTrue($account->fresh()->hasConfirmedTwoFactor());
    }
}
