<?php

namespace App\Actions\Fortify\TwoFactor;

use App\Domain\Platform\AuditReason;
use Laravel\Fortify\Actions\GenerateNewRecoveryCodes;

/** Fortify's action with an explicit audit reason for its write to the account (A5-04). */
class AuditedGenerateNewRecoveryCodes extends GenerateNewRecoveryCodes
{
    public function __invoke($user)
    {
        return app(AuditReason::class)->because('recovery codes regenerated by account holder', fn () => parent::__invoke($user));
    }
}
